/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JTextField;

import model.Model;
import model.enums.Vehicle;
import model.reservation.Reservation;
import model.reservation.Ticket;
import model.service.Service;
import model.service.ServiceProvider;

/**
 *
 * @author nelso
 */
public class AddServicesFrame extends javax.swing.JFrame {

        private Model model;
        private List<JFrame> ctx;
        private List<Ticket> tickets;
        private Vehicle vehicle;

        private List<Service> services;

        /**
         * Creates new form AddServicesFrame
         */
        public AddServicesFrame() {
                initComponents();
        }

        public AddServicesFrame(Model model, List<JFrame> ctx, List<Ticket> tickets, Vehicle vehicle) {
                this.model = model;
                this.ctx = ctx;
                this.tickets = tickets;
                this.services = new ArrayList<>();
                this.vehicle = vehicle;
                initComponents();
                initThings();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jSeparator2 = new javax.swing.JSeparator();
                jScrollPane1 = new javax.swing.JScrollPane();
                lstaddedServices = new javax.swing.JList<>();
                jLabel7 = new javax.swing.JLabel();
                cbxtype = new javax.swing.JComboBox<>();
                cbxname = new javax.swing.JComboBox<>();
                cbxservice = new javax.swing.JComboBox<>();
                btnaddService = new javax.swing.JButton();
                btndeleteService = new javax.swing.JButton();
                jSeparator3 = new javax.swing.JSeparator();
                jLabel8 = new javax.swing.JLabel();
                txtcost = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                btnconfirm = new javax.swing.JButton();
                btncancel = new javax.swing.JButton();
                txtitemPrice = jTextField4;

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel1.setText("Añadir servicios adicionales");

                jLabel2.setText("tipo:");

                jLabel3.setText("empresa:");

                jLabel4.setText("servicio:");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel5.setText("coste:");

                jTextField4.setEditable(false);
                jTextField4.setText("jTextField4");

                jLabel6.setText("Servicios añadidos");

                lstaddedServices.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jScrollPane1.setViewportView(lstaddedServices);

                jLabel7.setText("€");

                btnaddService.setText("Añadir servicio");
                btnaddService.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnaddServiceActionPerformed(evt);
                        }
                });

                btndeleteService.setText("Eliminar servicio");
                btndeleteService.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btndeleteServiceActionPerformed(evt);
                        }
                });

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel8.setText("coste total:");

                txtcost.setText("jTextField1");

                jLabel9.setText("€");

                btnconfirm.setText("Confirmar");
                btnconfirm.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnconfirmActionPerformed(evt);
                        }
                });

                btncancel.setText("Cancelar");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                208,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(46, 46, 46)
                                                                                                .addComponent(jSeparator1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                209,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel5,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                48,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jTextField4,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                107,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(jLabel7))
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                .addComponent(cbxservice,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                0,
                                                                                                                                                180,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(cbxname,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                0,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(cbxtype,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                0,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addComponent(jSeparator2,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                194,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(btncancel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                93,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(btnconfirm,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                93,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addComponent(jSeparator3)
                                                                                                                .addGap(12, 12, 12))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(btnaddService,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                127,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btndeleteService)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel8)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txtcost,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel9,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jSeparator1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                10,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel1))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel6)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jSeparator2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                10,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                138,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(40, 40, 40)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(cbxtype,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(cbxname,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(cbxservice,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addComponent(jTextField4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel7))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnaddService)
                                                                                .addComponent(btndeleteService)
                                                                                .addComponent(jLabel8)
                                                                                .addComponent(txtcost,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel9))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jSeparator3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnconfirm,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                38,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btncancel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                38,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(12, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnaddServiceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnaddServiceActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnaddServiceActionPerformed

        private void btndeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btndeleteServiceActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btndeleteServiceActionPerformed

        private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnconfirmActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnconfirmActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AddServicesFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AddServicesFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AddServicesFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AddServicesFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AddServicesFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnaddService;
        private javax.swing.JButton btncancel;
        private javax.swing.JButton btnconfirm;
        private javax.swing.JButton btndeleteService;
        private javax.swing.JComboBox<ServiceProvider> cbxname;
        private javax.swing.JComboBox<Service> cbxservice;
        private javax.swing.JComboBox<String> cbxtype;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JList<String> lstaddedServices;
        private javax.swing.JTextField txtcost;
        private JTextField txtitemPrice;

        // End of variables declaration//GEN-END:variables

        private void initThings() {

                cbxtype.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                model.getServiceTypes()
                                                                .toArray(new String[model.getServiceTypes().size()])));
                updateCbxname();
                updateCbxService();
                updatetxtitemPrice();
                updateLstaddedServices();

                cbxtype.addItemListener(e -> {
                        updateCbxname();
                        updateCbxService();
                        updatetxtitemPrice();
                });

                cbxname.addItemListener(e -> {
                        updateCbxService();
                        updatetxtitemPrice();
                });

                cbxservice.addItemListener(e -> {
                        updatetxtitemPrice();
                });

                btnaddService.addActionListener(e -> {

                        services.add((Service) cbxservice.getSelectedItem());
                        updateLstaddedServices();
                });

                btndeleteService.addActionListener(e -> {
                        services.remove(lstaddedServices.getSelectedIndex());
                        updateLstaddedServices();
                });

                btncancel.addActionListener(e -> {
                        JFrame frame = ctx.get(ctx.size() - 1);
                        ctx.remove(frame);
                        frame.setVisible(true);
                        this.dispose();
                });

                btnconfirm.addActionListener(e -> {
                        Reservation res = new Reservation(
                                        tickets.get(0).passenger(),
                                        new HashSet<>(tickets), null,
                                        vehicle,
                                        new HashSet<>(services));

                        ctx.add(this);
                        JFrame frame = new PayFrame(model, ctx, res);
                        this.setVisible(false);
                        frame.setVisible(true);
                });
        }

        private void updateCbxname() {
                cbxname.setModel(new javax.swing.DefaultComboBoxModel<>(
                                model.findServiceProvidersByType((String) cbxtype.getSelectedItem())
                                                .toArray(
                                                                new ServiceProvider[model.findServiceProvidersByType(
                                                                                (String) cbxtype.getSelectedItem())
                                                                                .size()])));

        }

        private void updateCbxService() {
                cbxservice.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                ((ServiceProvider) cbxname.getSelectedItem()).services().toArray(
                                                                new Service[((ServiceProvider) cbxname
                                                                                .getSelectedItem()).services()
                                                                                .size()])));

        }

        private void updatetxtitemPrice() {
                txtitemPrice.setText(Double.toString(((Service) cbxservice.getSelectedItem()).cost()));
        }

        private void updateLstaddedServices() {
                lstaddedServices.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = (String[]) services.stream().map(e -> e.description()).toList()
                                        .toArray(new String[services.size()]);

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });

                txtcost.setText(services.size() > 0
                                ? Double.toString(services.stream().map(elm -> elm.cost())
                                                .reduce((sum, acc) -> sum + acc).get())
                                : "0");
        }
}
