/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;

import model.Model;

/**
 *
 * @author nelso
 */
public class MainFrame extends javax.swing.JFrame {

        private Model model;

        public MainFrame(Model model) {
                this.model = model;
                initComponents();
                initThings();
                this.setVisible(true);
        }

        public MainFrame() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btntravel = new javax.swing.JButton();
                btnconsultReservation = new javax.swing.JButton();
                btnaddOpinion = new javax.swing.JButton();
                lblname = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btntravel.setText("Viajar");

                btnconsultReservation.setText("Consultar reservas");

                btnaddOpinion.setText("Añadir opinion");

                lblname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                lblname.setForeground(new java.awt.Color(51, 0, 255));
                lblname.setText("nombre");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblname,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                162,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btntravel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                125,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(btnconsultReservation)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                45,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnaddOpinion,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                125,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jSeparator1))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(lblname))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(jSeparator1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                10,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                73,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(btnaddOpinion,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                64,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnconsultReservation,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btntravel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(125, 125, 125)));

                pack();

        }// </editor-fold>//GEN-END:initComponents

        public void initThings() {

                // *=> code

                lblname.setText(model.company().name());

                btntravel.addActionListener(e -> {
                        List<JFrame> ctx = new ArrayList<>();
                        ctx.add(this);
                        this.setVisible(false);

                        ConsultScheduleFrame frame = new ConsultScheduleFrame(model, ctx);
                        frame.setVisible(true);
                });
                btnconsultReservation.addActionListener(e -> {
                        List<JFrame> ctx = new ArrayList<>();
                        ctx.add(this);
                        this.setVisible(false);
                        ConsultReserve frame = new ConsultReserve(model, ctx);
                        frame.setVisible(true);

                });
                btnaddOpinion.addActionListener(e -> {
                        List<JFrame> ctx = new ArrayList<>();
                        ctx.add(this);
                        this.setVisible(false);
                        AddComplaintFrame frame = new AddComplaintFrame(model, ctx);
                        frame.setVisible(true);
                });
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainFrame().setVisible(true);
                        }
                });

        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnaddOpinion;
        private javax.swing.JButton btnconsultReservation;
        private javax.swing.JButton btntravel;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel lblname;
        // End of variables declaration//GEN-END:variables
}
